image: docker.nix-community.org/nixpkgs/nix-flakes
build:
  stage: build
  script:
    - nix flake check -L
    - nix build -L
    - mkdir -p public
    - cp -r result/* public/
  artifacts:
    paths:
      - public
